### ISSUE TITLE
Preserve docs/CNAME

### ISSUE THREAD

**Issue by xatier** [victoriadrake/jekyll-cd#2]
The current `Clean site` stage will remove everything under the `docs` directory [1], including the important `CNAME` file for custom domain [2].

We can consider copying the `docs/CNAME` file for backup before deleting the directory.

[1] https://github.com/victoriadrake/jekyll-cd/blob/master/action.sh#L9
[2] https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by victoriadrake** [comment]
If you put your CNAME file in your [site](https://jekyllrb.com/docs/structure/) root, does it get built to `docs/CNAME` when the site builds? With Hugo it works similarly: you put the CNAME file in `static/` and it ends up in the built site's root.

**Comment by xatier** [comment]
Hi @victoriadrake, thanks for point this out. Yes, it seems that jekyll would put the `CNAME` file into `docs` if it's originally located in the site root. I guess we can drop this issue and my PR then?

**Comment by victoriadrake** [comment]
It appears so! I appreciate your effort to open it still! 😄 Thanks again!
